### ISSUE TITLE
How to reload captcha image with different numbers?

### ISSUE THREAD

**Issue by ghost** [napa3um/node-captcha#10]

**Comment by BookSong** [comment]
see my pull request here:
https://github.com/napa3um/node-captcha/pull/12

Basically, you can call 
<code>$("img").attr("src",$("img").attr("src") + "?somestring")</code>
if you are using jquery. 

but first you will have to make a small modification to captcha.js.

**Comment by napa3um** [comment]
Simple reload image on client.
