### ISSUE TITLE
Example code implementation errors.

### ISSUE THREAD

**Issue by Avaq** [napa3um/node-captcha#11]
Hi. I was looking over the source and I noticed that right now there might be several implementation errors in your example code:
- The problem mentioned in #9 which is easily solved by using secure cookies.
- Two problems with the way verification is done (`req.body.digits == req.session.captcha`)
  1. The `session.captcha` parameter is only _set_ when requesting the captcha image. Therefore a bad guy could just issue a `POST /login` directly (avoiding the captcha generation) and leave the `body.digits` to `undefined`. This effectively makes your code check: `undefined == undefined` which evaluates to `true`, granting access.
  2. Even after requesting the captcha image, and `session.captcha` has therefore been set, a bad guy might still remove their session cookie before submitting the form, and leave `body.digits` undefined. No session cookie sent means no session data looked up means the server is checking `undefined == undefined` again.

It's all just an implementation problem. It is solved by comparing in a more strict manner:

``` js
if(req.session.captcha && req.body.digits === req.session.captcha){
  //Request is valid.
}
```

However, your sample code doesn't implement it in this manner, but in a manner which will already be avoided by most bots (they tend to make direct requests to an API as explained in `i`). And since most people will work off the sample code there will probably already be some bad implementations out there.

I recommend that the example code is adjusted quite urgently and perhaps even a `captcha.verify()`-method exposed so that a user can be sure they're doing it right and potential future errors will get corrected retroactively.

**NOTE**: I haven't actually tested this theory. It's just some things I noticed skimming over the code while deciding whether to use this library. Do correct me if I'm wrong. :)

**Comment by napa3um** [comment]
Code updated, secure problems fixed.
