### ISSUE TITLE
Bots can get around this captcha system

### ISSUE THREAD

**Issue by emgram769** [napa3um/node-captcha#9]
The captcha answer is sent via cookie. What is the point of having a visual verification if the answer is in plain text? You should hash the answer so bots can't simply parse the it and send it back without ever looking at the captcha. Also in your demo use case you don't check for null==null, which would allow a bot to send a forged log in query.

**Comment by polkovnikov-ph** [comment]
The second project with security issues in documentation in the same day. Something's very wrong with Node.js community.

**Comment by napa3um** [comment]
Внимательно прочтите ветку, прежде чем делать столь глобальные обобщения. В любом случае у вас, как части комьюнити Node.JS, есть все возможности для того, чтобы помочь людям не допускать ошибок безопасности вместо того чтобы жаловаться, что этого не делают другие.

**Comment by polkovnikov-ph** [comment]
@napa3um А я внимательно прочитал. `cookie-session` это сугубо девелоперская штука, которой вообще, по-хорошему, не должно быть. Учитывая низкий уровень квалификации типичного веб-разработчика, оно в таком виде разлетается потом по продакшенам. Упоминание этой штуки в документации -- баг.

У меня прав записи на это репо нет. Попробуйте править баги быстрее, чем за два года, прежде чем советовать другим, как правильно помогать сообществу.

**Comment by napa3um** [comment]
Я вам что-то задолжал? Будьте любезны оплатить моё время, в том числе за участие в этой беседе, если решили учить меня, чем мне заниматься. Уроки делайте лучше и слушайтесь маму.

**Comment by napa3um** [comment]
Code updated, secure problems fixed.
